image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - java -jar ./artifacts/app-order.jar &
  - chmod +x gradlew
  - chmod +x ./driver/win/chromedriver.exe
build_script:
  - ./gradlew test --info "-Dselenide.headless=true"


